# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

pod 'couchbase-lite-ios', '~> 1.0.3.1'

target 'PullToRefresh+CouchbaseLite' do

end

target 'PullToRefresh+CouchbaseLiteTests' do

end

